"""relacionar books con authors

Revision ID: b4a93e7c8ffd
Revises: da16cffb9d8d
Create Date: 2026-10-03 13:20:45.685718

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b4a93e7c8ffd"
down_revision: str | Sequence[str] | None = "da16cffb9d8d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("books", sa.Column("author_id", sa.Integer(), nullable=False))
    op.create_index(op.f("ix_books_author_id"), "books", ["author_id"], unique=False)
    op.create_foreign_key(op.f("fk_books_author_id_authors"), "books", "authors", ["author_id"], ["id"])
    op.drop_column("books", "author")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("books", sa.Column("author", sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(op.f("fk_books_author_id_authors"), "books", type_="foreignkey")
    op.drop_index(op.f("ix_books_author_id"), table_name="books")
    op.drop_column("books", "author_id")
    # ### end Alembic commands ###
